---
title: "LWB Strategic Plans"
author: "Amy Shuff"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


``` {r, results='hide'}

# Only do this once:
# install.packages(c('knitr', 'usethis', 'tidyverse', 'janitor', 'reshape2', 'stringr', 'here', 'readxl', 'pdftools', 'tidytext'))

library(knitr)
library(usethis)
library(tidyverse)
library(janitor)
library(reshape2)
library(stringr)
library(here)
library(readxl)
library(pdftools)
library(tidytext)

```

```{r PDF Import, include=FALSE}

# PDF Strategic Plans
# Import all pdf files
pdf.file.list <- list.files(pattern='*.pdf', recursive = TRUE)
pdf.list <- sapply(pdf.file.list, pdf_text, simplify = FALSE, USE.NAMES = TRUE)

# pdf.file.list
# pdf.list


# File names to be joined with data later
pdf.names <- data.frame(pdf.file.list) %>% 
  mutate("Board Number" = row_number())
  
pdf.names <- pdf.names %>% 
  cbind(., Region = c("Panhandle", "South Plains", "North Texas", "North Central Texas", "Tarrant County", "Greater Dallas", "Northeast Texas", "East Texas", "West Central Texas", "Borderplex", "Permian-Basin", "Concho Valley", "Heart of Texas", "Capital Area", "Rural Capital Area", "Brazos Valley", "Deep East Texas", "Southeast Texas", "Golden Crescent", "Alamo", "South Texas", "Coastal Bend", "Lower Rio Grande Valley", "Cameron", "Texoma", "Central Texas", "Middle Rio Grande", "Gulf Coast")) 

pdf.names <- pdf.names %>% 
  mutate (
    Year = ifelse(endsWith(pdf.names$pdf.file.list, "2021.pdf"), "2021", ""),
    Year = ifelse(endsWith(pdf.names$pdf.file.list, "2023.pdf"), "2023", Year)
  )


```




```{r tidytext, include=FALSE}



pdf_df <- tibble(Text = pdf.list[["2023 Strategic Plans/101 Panhandle 2023.pdf"]]) %>%
  unnest_tokens(Word, Text) %>%
  mutate(
    pdf.file.list = "2023 Strategic Plans/101 Panhandle 2023.pdf")

pdf_df <- pdf_df %>% full_join(pdf.names)


# pdf.list[["2023 Strategic Plans/101 Panhandle 2023.pdf"]]


word.list <- list()

for(pdf in 1:max(row_number(pdf.file.list))){
  
    pdf_df <- tibble(Text = pdf.list[[pdf]]) %>%
      unnest_tokens(Word, Text) %>%
      mutate(
        pdf.file.list = paste(pdf))
    
    word.list[[pdf]] <- pdf_df
    
    }

# UPDATE: Board 11 is not a pdf with select-able text



words <- bind_rows(list(word.list), .id = "Board Number") %>%
    mutate("Board Number" = as.numeric("Board Number")) 

# UPDATE: Board Number is not behaving properly with as.numeric

# %>% 
#     full_join(pdf.names, by = "Board Number")


```









```{r, include=FALSE}

```



